name: dependency_injector
description: A dependency injection system for Flutter that automatically calls cancel, close and dispose methods, if any.
version: 0.1.0+2
homepage: https://github.com/vr19860507/dependency_injector

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  strict_analyzer: ^0.6.0

flutter:
